spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product
    username: root
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
server:
  port: 8084